services:
  jenkins:
    container_name: jenkins_ansible
    image: jenkins-ansible
    build:
      context: ./jenkins-ansible
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net
  remote_host:
    container_name: remote_host_jenkins
    image: remote-host
    build:
      context: ./virtual-machine
    volumes:
      - $PWD/virtual-machine/data:/home/remote_user/data
    networks:
      - net
  remote_host_second:
    container_name: remote_host_second_jenkins
    image: remote-host-second
    build:
      context: ./virtual-machine-second
    volumes:
      - $PWD/virtual-machine-second/data:/home/reza/data
    networks:
      - net
  db_host:
    container_name: db_postgresql_jenkins
    image: postgres:14.17-bookworm
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - $PWD/postgresql_data:/var/lib/postgresql/data
    networks:
      - net
  web:
    container_name: web_jenkins
    image: ansible-web
    build:
      context: ./jenkins-ansible/web
    ports:
      - "80:80"
    volumes:
      - $PWD/jenkins-ansible/web/www/html:/var/www/html
    networks:
      - net
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    platform: linux/amd64
    ports:
      - '8090:80'
      - '443:443'
      - '22:22'
    volumes:
      - $PWD/gitlab_home/config:/etc/gitlab
      - $PWD/gitlab_home/logs:/var/log/gitlab
      - $PWD/gitlab_home/data:/var/opt/gitlab
    shm_size: '256m'
    networks:
      - net
networks:
  net: